image: amazon/aws-cli:2.2.46

definitions:
  steps:
    - step: &publish_step
        name: Publish docker image to ECR
        caches:
          - docker
        services:
          - docker
        script:
          - ENV="$BITBUCKET_BRANCH"
          - REGISTRY=558222663521.dkr.ecr.eu-west-1.amazonaws.com
          - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin $REGISTRY
          
          - docker build -t rqr/pdf-classifier-lambda .

          - docker tag rqr/pdf-classifier-lambda:latest $REGISTRY/rqr/pdf-classifier-lambda:$ENV-$BITBUCKET_COMMIT
          - docker push $REGISTRY/rqr/pdf-classifier-lambda:$ENV-$BITBUCKET_COMMIT
          
          - docker tag rqr/pdf-classifier-lambda:latest $REGISTRY/rqr/pdf-classifier-lambda:$ENV-latest
          - docker push $REGISTRY/rqr/pdf-classifier-lambda:$ENV-latest
    - step: &deploy_step
        name: Deploy to AWS Lambda
        trigger: manual
        script:
          - ENV="$BITBUCKET_BRANCH"
          - REGISTRY=558222663521.dkr.ecr.eu-west-1.amazonaws.com
          - aws lambda update-function-code --region eu-west-1 --function-name "rqr-pdf-classifier-lambda-$ENV" --image-uri $REGISTRY/rqr/pdf-classifier-lambda:$ENV-$BITBUCKET_COMMIT

pipelines:
  branches:
    recette:
      - step: *publish_step
      - step: *deploy_step
    demo:
      - step: *publish_step
      - step: *deploy_step
    prod:
      - step: *publish_step
      - step: *deploy_step
